### ISSUE TITLE
FTP Transfer Speeds to MGMT1 are slow

### ISSUE THREAD

**Issue by djrotenberg** [CAMH-Scientific-Computing/SCC#22]
The transfer speeds to managment 1 are relatively slow from the Ilumina sequencer. 

Curr: 37.86 MBit/s
Avg: 42.84 MBit/s
Min: 8.82 MBit/s
Max: 134.54 MBit/s
Ttl: 820.51 GByte

We should investigate whether this is a general issue affecting management 1.

**Comment by pipitone** [comment]
This may also be related to the poor disk I/O speeds we were seeing.

**Comment by djrotenberg** [comment]
This could be the case. I would like to schedule a test of the SAS cable(s) if possible during the next maintenance phase. In this case the data are being written to one of the PI arrays. 

hdparm -Tt /dev/mapper/epigenetics-epigenetics_scratch

/dev/mapper/epigenetics-epigenetics_scratch:
 Timing cached reads:   15094 MB in  2.00 seconds = 7556.48 MB/sec
 Timing buffered disk reads:  518 MB in  3.01 seconds = 172.22 MB/sec

**Comment by pipitone** [comment]
For reference, the kimel lab StorWise array, with only one controller,
and a busy queue of jobs: 

$ sudo hdparm -Tt /dev/mapper/vg_volumen0-lv_quarantine2

/dev/mapper/vg_volumen0-lv_quarantine2:
 Timing cached reads:   15888 MB in  2.00 seconds = 7949.03 MB/sec
 Timing buffered disk reads: 862 MB in  3.01 seconds = 286.73 MB/sec

**Comment by qchang** [comment]
I have done a bit of testing on mgmt2 using dd and scp.

NFS performance (tested per dd) between mgmt1 and mgmt2 is quite good, essentially wire speed (see wMB_svr/s colume) below. 

Transfer per scp is quite a bit slower. This is probably due to the fact that the traffic goes through firewall and we are using ssh protocol.

Perceived transfer rate for NFS with no firewall involved is from 80MB/s to close to 100MB/s while that for scp is only 35MB/s.

----- test results for reference -----

# dd, NFS between mgmt1(server) and mgmt2(client):

# chunk of 512bytes:

qchang@mgmt2 ~]$ date;time dd if=/dev/zero of=testio bs=512 count=20M
Thu Apr  2 11:38:21 EDT 2015
20971520+0 records in
20971520+0 records out
10737418240 bytes (11 GB) copied, 116.679 s, 92.0 MB/s
real    1m56.704s
user    0m1.385s
sys 0m21.298s
[qchang@mgmt2 ~]$ iostat -xmn  10|egrep "MRI"
Filesystem:               rMB_nor/s    wMB_nor/s    rMB_dir/s    wMB_dir/s    rMB_svr/s    wMB_svr/s     ops/s    rops/s    wops/s
mgmt1:/imaging/home/MRI         0.00         0.04         0.00         0.00         0.00         0.04    109.16      0.00      0.04
mgmt1:/imaging/home/MRI         0.00       270.42         0.00         0.00         0.00        13.90     19.20      0.00     13.90
mgmt1:/imaging/home/MRI         0.00       141.67         0.00         0.00         0.00       107.20    110.10      0.00    107.20
mgmt1:/imaging/home/MRI         0.00         0.18         0.00         0.00         0.00       107.60    113.80      0.00    107.60
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       108.90    110.60      0.00    108.90
mgmt1:/imaging/home/MRI         0.00        51.48         0.00         0.00         0.00        75.37     77.90      0.00     76.50
mgmt1:/imaging/home/MRI         0.00       167.72         0.00         0.00         0.00        67.70     69.00      0.00     67.70
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       104.80    111.00      0.00    104.80
mgmt1:/imaging/home/MRI         0.00       142.11         0.00         0.00         0.00        74.01     75.40      0.00     74.20
mgmt1:/imaging/home/MRI         0.00         0.66         0.00         0.00         0.00       107.20    108.00      0.00    107.20
mgmt1:/imaging/home/MRI         0.00       143.10         0.00         0.00         0.00        71.50     72.80      0.00     71.60

## mgmt1:/imaging/home/MRI         0.00       106.67         0.00         0.00         0.00        81.96     82.30      0.00     82.00

# chunk of 1K:

[qchang@mgmt2 ~]$ date;time dd if=/dev/zero of=testio bs=1K count=10M
Thu Apr  2 11:51:20 EDT 2015
dd: writing `testio': No space left on device
9097400+0 records in
9097399+0 records out
9315736576 bytes (9.3 GB) copied, 94.8581 s, 98.2 MB/s
real    1m34.893s
user    0m0.596s
sys 0m12.506s
mgmt1:/imaging/home/MRI         0.00         0.04         0.00         0.00         0.00         0.04    109.14      0.00      0.04
mgmt1:/imaging/home/MRI         0.00        81.21         0.00         0.00         0.00         0.00      0.50      0.00      0.00
mgmt1:/imaging/home/MRI         0.00       389.49         0.00         0.00         0.00        89.10     89.50      0.00     89.10
mgmt1:/imaging/home/MRI         0.00        53.27         0.00         0.00         0.00       107.40    109.30      0.00    107.40
mgmt1:/imaging/home/MRI         0.00        73.52         0.00         0.00         0.00       106.90    107.30      0.00    106.90
mgmt1:/imaging/home/MRI         0.00         0.30         0.00         0.00         0.00       107.80    108.00      0.00    107.80
mgmt1:/imaging/home/MRI         0.00         0.29         0.00         0.00         0.00       107.10    107.10      0.00    107.10
mgmt1:/imaging/home/MRI         0.00         0.20         0.00         0.00         0.00        79.78     79.80      0.00     79.90
mgmt1:/imaging/home/MRI         0.00       228.89         0.00         0.00         0.00        60.62     62.20      0.00     60.70
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       107.10    109.80      0.00    107.10

## mgmt1:/imaging/home/MRI         0.00        61.24         0.00         0.00         0.00        99.17    100.30      0.00     99.20

# chunk of 2K:

[qchang@mgmt2 ~]$ date;time dd if=/dev/zero of=testio bs=2K count=5M
Thu Apr  2 11:58:53 EDT 2015
dd: writing `testio': No space left on device
4795570+0 records in
4795569+0 records out
9821325312 bytes (9.8 GB) copied, 122.209 s, 80.4 MB/s

real    2m2.215s
user    0m0.360s
sys 0m9.225s
mgmt1:/imaging/home/MRI         0.00       311.63         0.00         0.00         0.00        14.40     16.60      0.00     14.40
mgmt1:/imaging/home/MRI         0.00       108.99         0.00         0.00         0.00       107.90    107.90      0.00    107.90
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       107.00    107.00      0.00    107.00
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00         8.90     10.30      0.00      8.90
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00         0.00      0.00      0.00      0.00
mgmt1:/imaging/home/MRI         0.00       229.34         0.00         0.00         0.00        53.00     55.10      0.00     53.00
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       106.80    107.20      0.00    106.80
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       107.27    107.40      0.00    107.30
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       108.60    108.50      0.00    108.60

## mgmt1:/imaging/home/MRI         0.00       286.67         0.00         0.00         0.00        67.57     68.10      0.00     67.60

# chunk of 4K:

[qchang@mgmt2 ~]$ date;time dd if=/dev/zero of=testio bs=4K count=2M
Thu Apr  2 12:03:07 EDT 2015
2097152+0 records in
2097152+0 records out
8589934592 bytes (8.6 GB) copied, 80.4917 s, 107 MB/s
real    1m20.496s
user    0m0.230s
sys 0m6.757s
mgmt1:/imaging/home/MRI         0.00         0.06         0.00         0.00         0.00         0.06    109.12      0.00      0.06
mgmt1:/imaging/home/MRI         0.00       419.67         0.00         0.00         0.00        41.80     42.50      0.00     41.80
mgmt1:/imaging/home/MRI         0.00       106.84         0.00         0.00         0.00       108.30    108.80      0.00    108.30
mgmt1:/imaging/home/MRI         0.00        17.60         0.00         0.00         0.00       107.60    107.70      0.00    107.60
mgmt1:/imaging/home/MRI         0.00       193.42         0.00         0.00         0.00       108.40    110.70      0.00    108.40
mgmt1:/imaging/home/MRI         0.00        29.20         0.00         0.00         0.00       108.50    108.70      0.00    108.50
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       108.80    108.90      0.00    108.80
mgmt1:/imaging/home/MRI         0.00         0.00         0.00         0.00         0.00       106.40    107.70      0.00    106.40
mgmt1:/imaging/home/MRI         0.00        52.47         0.00         0.00         0.00        81.93     80.90      0.00     82.00

# scp from ub1404, steady at around 37MB/s and real perceived rate 35MB/s:

qchang@ub1404:~/CAMH$ time scp testio qchang@192.168.214.10:~/
testio                                                           100%   10GB  36.1MB/s   04:44  
real    4m51.640s
user    1m11.150s

## sys 1m25.816s

**Comment by andycamh** [comment]
After multipath maintenance , general write speed on mgmt1 can get 180MB/s,use David's old parameter test result: 

date;time dd if=/dev/zero of=testio bs=4K count=2M
Tue Dec 22 15:02:42 EST 2015
2097152+0 records in
2097152+0 records out
8589934592 bytes (8.6 GB) copied, 10.3996 s, 826 MB/s

real    0m10.408s
user    0m0.290s
sys     0m10.117s
